package com.cussou.autotiq.ui.settings

import com.cussou.autotiq.domain.model.MapPoint

/**
 * Models for zone import/export functionality
 * Uses Gson for JSON serialization/deserialization
 */

data class ZoneExportWrapper(
    val version: Int = 1,
    val exportDate: String, // ISO-8601 format
    val zones: List<ZoneExport>
)

data class ZoneExport(
    val name: String,
    val latitude: Double,
    val longitude: Double,
    val startHour: Int,
    val startMinute: Int,
    val endHour: Int,
    val endMinute: Int
)

/**
 * Converts a domain MapPoint to an exportable ZoneExport
 * Note: We don't export id or createdAt (will be regenerated on import)
 */
fun MapPoint.toZoneExport() = ZoneExport(
    name = name,
    latitude = latitude,
    longitude = longitude,
    startHour = startHour,
    startMinute = startMinute,
    endHour = endHour,
    endMinute = endMinute
)

/**
 * Converts an imported ZoneExport to a domain MapPoint
 * Note: id and createdAt will be set by the database
 */
fun ZoneExport.toMapPoint() = MapPoint(
    id = 0, // Will be auto-generated by database
    name = name,
    latitude = latitude,
    longitude = longitude,
    startHour = startHour,
    startMinute = startMinute,
    endHour = endHour,
    endMinute = endMinute,
    createdAt = System.currentTimeMillis()
)
